# Production credentials template
# Run: EDITOR=nano bin/rails credentials:edit --environment production
# Then add these values:

postmark_api_token: YOUR_POSTMARK_API_TOKEN_HERE
base_url: remindly.anakhsoft.com
admin_email: noreply@remindly.anakhsoft.com

# Used as the base secret for all MessageVerifiers in Rails
secret_key_base: (already set - don't change)
