# frozen_string_literal: true

require "csv"
require "net/http"

namespace :area_codes do
  # NANPA publishes the list of North American area codes and where each one
  # is. This rewrites config/area_codes.yml from that file. New codes are added
  # a few times a year; a code missing from the table only means the phone
  # panel says nothing about it, so a stale table is harmless, just less useful.
  #
  # State or province only, never a city: one area code covers a region, and a
  # single city name would be wrong for most of the people it names.
  desc "Rewrite config/area_codes.yml from NANPA's area code report"
  task refresh: :environment do
    source = "https://reports.nanpa.com/public/npa_report.csv"
    body = Net::HTTP.get_response(URI(source)).tap(&:value).body

    file_date = body.lines.first.to_s[/File Date,(.+)/, 1]&.strip
    rows = CSV.parse(body.lines.drop(1).join, headers: true)

    # Refuse anything that does not look like NANPA's report before touching
    # the table: an error page served as 200, an empty body or a renamed column
    # would otherwise produce an empty map and overwrite the good one, and the
    # panel would quietly stop saying anything for everybody.
    missing = %w[NPA_ID USE IN_SERVICE LOCATION] - rows.headers.compact
    abort "NANPA's report is missing #{missing.join(', ')}; config/area_codes.yml left as it was." if missing.any?
    abort "NANPA's report has no file date; config/area_codes.yml left as it was." if file_date.blank?

    # Geographic codes in service only. Toll-free, premium and the other
    # non-geographic codes have no place to name.
    regions = rows
      .select { |row| row["USE"] == "G" && row["IN_SERVICE"] == "Y" && row["LOCATION"].present? }
      .to_h { |row| [ row["NPA_ID"], AreaCode.region_name(row["LOCATION"]) ] }
      .sort.to_h

    # There are about 450; a count far below that is a partial or broken file.
    minimum = 400
    if regions.size < minimum
      abort "Only #{regions.size} area codes in NANPA's report, expected #{minimum}+; " \
            "config/area_codes.yml left as it was."
    end

    header = <<~YAML
      # Area code -> the state, province or country it belongs to.
      # Generated by `bin/rails area_codes:refresh` from #{source}
      # (NANPA file date #{file_date}). Do not edit by hand; rerun the task.
    YAML

    # Written to a temporary file and renamed over the table, so an interrupted
    # run leaves the old table whole rather than a truncated one.
    File.atomic_write(Rails.root.join("config/area_codes.yml")) do |file|
      file.write(header + regions.to_yaml.delete_prefix("---\n"))
    end
    puts "Wrote #{regions.size} area codes (NANPA file date #{file_date})."
  end
end
